### ISSUE TITLE
Allow attachments in transactions

### ISSUE THREAD

**Issue by fmartingr** [dsaltares/finlight-electron#4]
Allowing attachments in transactions is very useful to avoid having split transactions where you adquired multiple items (eg: groceries).

In my experience it's easy to link a transaction to an individual item (when you buy one thing), but when you go grocery shopping you do one payment but buy multiple things. I don't want to split that payment into the individual items because most times I don't need to split that into several categories but I still do want to capture the prices for history purposes (and, maybe in the far future, OCR search?). 

Even for single items you could store the receipt in case you need it in the future for warranty purposes, though in that case maybe a link to external storage is more useful.

**Comment by dsaltares** [comment]
Just adding some sub-issues.

- [ ] Design local file structure for attached files
- [ ] Data model and migrations to support file attachments to transactions
- [ ] Support attachments in tRPC procedures
- [ ] Attachment preview
- [ ] Attachment CRUD UI

**Comment by dsaltares** [comment]
# Local file structure for attached files

We'll have one "`data`" folder, inside, we'll put:
- `db.sqlite`
- `attachments` folder
  - `[transactionId]` folders to indicate which transaction the files are associated to. Inside, we'll have all attachments for that transactions in a flat structure.

`userSettings.json` will need to change structure from

```json
{
  "dbPath": "[...]/finlight.sqlite"
}
```

to something like

```json
{
  "dataPath": "[...]/finlight"
}
```

We could have 2 settings, one for the attachments' location and another for the db location, but I think it's nicer and simpler to keep them together.

This is a config backwards incompatible change. There's no user base to maintain, so I'm just going to break compatibility. However, in order to be nicer about this going forward, even if just for my sake, I will make it easier by:

```json
{
  "version": 1,
  "settings": {
    "dataPath": "[...]/finlight"
  }
}
```

## Alternatives considered

We though of using [SQLite Blobs](https://www.sqlite.org/datatype3.html) for files, which would work quite nicely. However, there's a few issues:
- Cloud storage services like Google Drive don't support syncing updates only, the entire database needs to be synced every time it changes. Even if we keep blobs in a separate SQLite, we'd have to re-sync all attachments every time.
- It's a bit slower than raw file access.

**Comment by fmartingr** [comment]
> `attachments` folder
> * `[transactionId]` folders to indicate which transaction the files are associated to. Inside, we'll have all attachments for that transactions in a flat structure.

Better having all attachments in the same folder than distributing them in `year/month` subfolders? What happens if a transaction has more than one attachment?

**Comment by dsaltares** [comment]
I wanted to keep the structure as simple as possible.

> What happens if a transaction has more than one attachment?

All attachments for a given transaction will live in the same folder. There can't be 2 attachments in the same transactions with the same filename. This is enforced as well by a unique constraint at the db level: https://github.com/dsaltares/finlight-electron/pull/16/files#diff-84ed7d3e4d9d5c9c18074f0fac0eca077009db08c000992e1028c1ab6c6910eeR22.
